import mongoose, { Schema, Document, Types } from 'mongoose';

export const COLUMN_IDS = ['todo', 'in-progress', 'review', 'done'] as const;
export const PRIORITIES = ['low', 'medium', 'high'] as const;
export const LABELS = [
  'copywriting',
  'design',
  'illustration',
  'research',
] as const;
export const SEVERITIES = ['trivial', 'minor', 'major', 'critical', 'blocker'] as const;

export type ColumnId = (typeof COLUMN_IDS)[number];
export type Priority = (typeof PRIORITIES)[number];
export type LabelType = (typeof LABELS)[number];
export type Severity = (typeof SEVERITIES)[number];

export interface Subtask {
  id: string;
  title: string;
  done: boolean;
}

export interface ChecklistItem {
  id: string;
  text: string;
  checked: boolean;
}

export interface Recurrence {
  frequency: 'daily' | 'weekly' | 'monthly' | 'none';
  interval: number;
  endsOn: string;
}

export interface ITask extends Document {
  _id: Types.ObjectId;
  owner: Types.ObjectId;
  organization: Types.ObjectId | null;
  project: Types.ObjectId | null;
  clientId: string;
  title: string;
  description: string;
  column: ColumnId;
  priority: Priority;
  label: LabelType;
  severity: Severity;
  reviewer: string;
  storyPoints: number;
  estimatedEffort: number;
  dependencies: string[];
  subtasks: Subtask[];
  checklist: ChecklistItem[];
  recurrence: Recurrence;
  createdBy: string;
  dueDate: string;
  assignee: string;
  comments: number;
  attachments: number;
  boardIndex: number;
  listIndex: number;
  createdAtISO: string;
}

const taskSchema = new Schema<ITask>(
  {
    owner: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    organization: {
      type: Schema.Types.ObjectId,
      ref: 'Organization',
      default: null,
      index: true,
    },
    project: {
      type: Schema.Types.ObjectId,
      ref: 'Project',
      default: null,
      index: true,
    },
    // Stable id generated by the client so offline edits reconcile cleanly.
    clientId: { type: String, required: true },

    title: { type: String, required: true, trim: true, maxlength: 200 },
    description: { type: String, default: '', maxlength: 5000 },
    column: { type: String, enum: COLUMN_IDS, default: 'todo' },
    priority: { type: String, enum: PRIORITIES, default: 'medium' },
    label: { type: String, enum: LABELS, default: 'design' },
    severity: { type: String, enum: SEVERITIES, default: 'minor' },
    reviewer: { type: String, default: '' },
    storyPoints: { type: Number, default: 0, min: 0 },
    estimatedEffort: { type: Number, default: 0, min: 0 },
    dependencies: { type: [String], default: [] },
    subtasks: {
      type: [
        {
          id: { type: String, required: true },
          title: { type: String, required: true, maxlength: 300 },
          done: { type: Boolean, default: false },
        },
      ],
      default: [],
    },
    checklist: {
      type: [
        {
          id: { type: String, required: true },
          text: { type: String, required: true, maxlength: 500 },
          checked: { type: Boolean, default: false },
        },
      ],
      default: [],
    },
    recurrence: {
      type: {
        frequency: {
          type: String,
          enum: ['daily', 'weekly', 'monthly', 'none'],
          default: 'none',
        },
        interval: { type: Number, default: 1, min: 1, max: 365 },
        endsOn: { type: String, default: '' },
      },
      default: { frequency: 'none', interval: 1, endsOn: '' },
    },
    createdBy: { type: String, default: '' },
    dueDate: { type: String, default: '' },
    assignee: { type: String, default: 'Me' },
    comments: { type: Number, default: 0, min: 0 },
    attachments: { type: Number, default: 0, min: 0 },
    boardIndex: { type: Number, default: 0 },
    listIndex: { type: Number, default: 0 },
    createdAtISO: { type: String, default: () => new Date().toISOString() },
  },
  { timestamps: true }
);

taskSchema.index({ owner: 1, clientId: 1 }, { unique: true });

export default mongoose.model<ITask>('Task', taskSchema);
