import mongoose, { Schema, Document, Types } from 'mongoose';

export const COLUMN_IDS = ['todo', 'in-progress', 'review', 'done'] as const;
export const PRIORITIES = ['low', 'medium', 'high'] as const;
export const LABELS = [
  'copywriting',
  'design',
  'illustration',
  'research',
] as const;

export type ColumnId = (typeof COLUMN_IDS)[number];
export type Priority = (typeof PRIORITIES)[number];
export type LabelType = (typeof LABELS)[number];

export interface ITask extends Document {
  _id: Types.ObjectId;
  owner: Types.ObjectId;
  clientId: string;
  title: string;
  description: string;
  column: ColumnId;
  priority: Priority;
  label: LabelType;
  dueDate: string;
  assignee: string;
  comments: number;
  attachments: number;
  boardIndex: number;
  listIndex: number;
  createdAtISO: string;
}

const taskSchema = new Schema<ITask>(
  {
    owner: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    // Stable id generated by the client so offline edits reconcile cleanly.
    clientId: { type: String, required: true },
    title: { type: String, required: true, trim: true, maxlength: 200 },
    description: { type: String, default: '', maxlength: 5000 },
    column: { type: String, enum: COLUMN_IDS, default: 'todo' },
    priority: { type: String, enum: PRIORITIES, default: 'medium' },
    label: { type: String, enum: LABELS, default: 'design' },
    dueDate: { type: String, default: '' },
    assignee: { type: String, default: 'Me' },
    comments: { type: Number, default: 0, min: 0 },
    attachments: { type: Number, default: 0, min: 0 },
    boardIndex: { type: Number, default: 0 },
    listIndex: { type: Number, default: 0 },
    createdAtISO: { type: String, default: () => new Date().toISOString() },
  },
  { timestamps: true }
);

taskSchema.index({ owner: 1, clientId: 1 }, { unique: true });

export default mongoose.model<ITask>('Task', taskSchema);
