import type { Task } from "./types";

export const INITIAL_TASKS: Task[] = [
  {
    id: "t1",
    title: "Konsep hero title yang menarik",
    description: "Buat beberapa opsi headline untuk homepage.",
    column: "todo",
    priority: "medium",
    label: "copywriting",
    dueDate: "Nov 24",
    assignee: "A",
    comments: 2,
    attachments: 1,
    createdAt: new Date().toISOString(),
  },
  {
    id: "t2",
    title: "Membuat konsep ilustrasi untuk halaman about us",
    description: "Sketsa ilustrasi tim dan nilai perusahaan.",
    column: "in-progress",
    priority: "high",
    label: "illustration",
    dueDate: "Nov 24",
    assignee: "B",
    comments: 3,
    attachments: 2,
    createdAt: new Date().toISOString(),
  },
  {
    id: "t3",
    title: "Membuat konsep ilustrasi untuk halaman about us",
    description: "Revisi warna dan komposisi ilustrasi.",
    column: "review",
    priority: "medium",
    label: "design",
    dueDate: "Nov 24",
    assignee: "C",
    comments: 2,
    attachments: 1,
    createdAt: new Date().toISOString(),
  },
  {
    id: "t4",
    title: "Membuat konsep ilustrasi untuk halaman about us",
    description: "Finalisasi asset untuk halaman about.",
    column: "done",
    priority: "low",
    label: "illustration",
    dueDate: "Nov 24",
    assignee: "D",
    comments: 5,
    attachments: 3,
    createdAt: new Date().toISOString(),
  },
  {
    id: "t5",
    title: "Icon di section our services",
    description: "Buat set icon 24px untuk layanan.",
    column: "todo",
    priority: "low",
    label: "design",
    dueDate: "Nov 24",
    assignee: "E",
    comments: 1,
    attachments: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "t6",
    title: "Membuat konsep ilustrasi untuk halaman about us",
    description: "Eksplorasi gaya ilustrasi flat 3D.",
    column: "in-progress",
    priority: "medium",
    label: "copywriting",
    dueDate: "Nov 24",
    assignee: "F",
    comments: 2,
    attachments: 1,
    createdAt: new Date().toISOString(),
  },
  {
    id: "t7",
    title: "Membuat konsep ilustrasi untuk halaman about us",
    description: "Sunting copy untuk halaman about.",
    column: "review",
    priority: "high",
    label: "copywriting",
    dueDate: "Nov 24",
    assignee: "G",
    comments: 4,
    attachments: 2,
    createdAt: new Date().toISOString(),
  },
  {
    id: "t8",
    title: "Membuat konsep ilustrasi untuk halaman about us",
    description: "Kompilasi feedback dari stakeholder.",
    column: "done",
    priority: "medium",
    label: "design",
    dueDate: "Nov 24",
    assignee: "H",
    comments: 2,
    attachments: 1,
    createdAt: new Date().toISOString(),
  },
  {
    id: "t9",
    title: "Research competitor landing pages",
    description: "Analisis 5 kompetitor utama.",
    column: "todo",
    priority: "high",
    label: "research",
    dueDate: "Nov 25",
    assignee: "I",
    comments: 3,
    attachments: 4,
    createdAt: new Date().toISOString(),
  },
  {
    id: "t10",
    title: "Draft value proposition",
    description: "Tulis value prop untuk hero section.",
    column: "in-progress",
    priority: "medium",
    label: "copywriting",
    dueDate: "Nov 25",
    assignee: "J",
    comments: 1,
    attachments: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "t11",
    title: "Color palette exploration",
    description: "Eksplorasi palet warna brand.",
    column: "review",
    priority: "low",
    label: "design",
    dueDate: "Nov 25",
    assignee: "K",
    comments: 2,
    attachments: 2,
    createdAt: new Date().toISOString(),
  },
  {
    id: "t12",
    title: "Final homepage illustration",
    description: "Asset final untuk development handoff.",
    column: "done",
    priority: "high",
    label: "illustration",
    dueDate: "Nov 25",
    assignee: "L",
    comments: 6,
    attachments: 5,
    createdAt: new Date().toISOString(),
  },
];

export const ACTIVITIES = [
  { id: 1, user: "Andrea", action: "uploaded 3 documents", time: "Aug 15", color: "bg-amber-400" },
  { id: 2, user: "Karen", action: "left some comments", time: "Aug 15", color: "bg-emerald-400" },
  { id: 3, user: "Karen", action: "changed project description", time: "Aug 15", color: "bg-indigo-400" },
  { id: 4, user: "Andrea", action: "uploaded 3 documents", time: "Aug 15", color: "bg-amber-400" },
  { id: 5, user: "Karen", action: "left some comments", time: "Aug 15", color: "bg-emerald-400" },
];
